name: fitflow
description: "Modern athlete tracking app for fitness trainers"
publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  # Supabase
  supabase_flutter: ^2.9.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  # State Management
  provider: ^6.1.1

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
  google_fonts: ^6.1.0

  # Charts
  fl_chart: ^0.66.0

  # Date/Time
  intl: ^0.19.0

  # Utilities
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  signature: ^5.5.0
  table_calendar: ^3.1.3
  emoji_picker_flutter: ^4.4.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  googleapis_auth: ^2.0.0

  google_sign_in: ^6.2.1
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#000000"
    theme_color: "#000000"


flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/icon/
    - assets/service_account.json
